Add space and subnet to schema
manadart/squju pull request #2
Opened 2022-04-11 14:07 UTC by jack-w-shaw

Add space and subnet to schema

Also add `IF NOT EXISTS` to indexes and `provider` table for relations

2022-04-11 15:18 UTC, manadart requested changes
We don't need the provider table. PROVIDER_ID is the provider's ID for the entity. We currently have a collection providerIDs, which tracks these across different entity types, but I'd leave that for now. Just put a unique index on it.

2022-04-11 16:14 UTC, jack-w-shaw commented
Fixed, ready for another look over

2022-04-12 08:24 UTC, manadart requested changes
One nit.

2022-04-12 08:24 UTC, manadart commented on schema.ddl
> +CREATE UNIQUE INDEX IF NOT EXISTS idx_space_provider_id
Should be for subnet provider ID.

2022-04-12 08:41 UTC, jack-w-shaw commented on schema.ddl
> +CREATE UNIQUE INDEX IF NOT EXISTS idx_space_provider_id
resolved

2022-04-12 09:19 UTC, manadart approved these changes

2022-04-12 09:20 UTC, merged